import { readFileSync } from "node:fs";
import { test, expect, type Page } from "@playwright/test";
import { readField, type FieldState } from "./drawing";

/**
 * The redesigned drawings keep everything the deployed ones said, except
 * where the September 29 review (issue #74) changed it on purpose.
 *
 * The fixture is an inventory of the drawings as deployed at the commit it
 * names, generated by `scripts/diagram-inventory.mjs` from that commit's own
 * modules: every word, its kind and its beat, every connection including the
 * feedback loops and the unlabelled branches, every mark on a person, a check
 * or a result, and each drawing's description and caption. The artwork was
 * redrawn from nothing; none of that was allowed to change. It was then
 * revised by hand, not regenerated, for the review's intentional changes: a
 * Design step before Test, an illustrative Claude Daily Brief for executives,
 * a whiteboard-to-keyboard Workshops drawing and the teams-and-contributors
 * name and gate.
 */

type Link = { from: string; to: string; weight: string };
type Inventory = {
  source: string;
  schematics: {
    id: string;
    description: string;
    nodes: { id: string; label: string; kind: string }[];
    flow: Record<"landscape" | "portrait", Link[]>;
  }[];
  scenes: {
    id: string;
    description: string;
    landscape: Scene;
    portrait: Scene;
  }[];
  captions: { id: string; caption: string }[];
};
type Scene = {
  labels: { text: string; kind: string; beat: number }[];
  marks: { kind: string; beat: number }[];
};

const inventory = JSON.parse(
  readFileSync(
    new URL("./fixtures/diagram-inventory.json", import.meta.url),
    "utf8",
  ),
) as Inventory;

/**
 * The scenes' connections, read from the deployed drawings' routes: which
 * piece each route ran from and to. The executive view feeds back to the
 * problem it answers; each role's skill answers to the human in the loop; the
 * builder's workflow is three linked parts; the review passes the three checks
 * in order before a person, then the business.
 */
const sceneLinks: Record<string, string[]> = {
  executives: [
    "problem>skill",
    "skill>brief",
    "direction>brief",
    "brief>problem",
  ],
  contributors: [
    ...[1, 2, 3, 4].flatMap((n) => [`role${n}>skill${n}`, `skill${n}>human`]),
    "human>result",
  ],
  builders: [
    "learner>design",
    "design>test",
    "test>troubleshoot",
    "troubleshoot>anticipate",
    "anticipate>workflow",
    "workflow>blocks",
  ],
  review: [
    "draft>weak",
    "weak>missing",
    "missing>false",
    "false>review",
    "review>business",
  ],
};

const drawnLinks = (state: FieldState) =>
  [...new Set(state.parts.flatMap((piece) => piece.links))].sort();
const drawnNodes = (state: FieldState) =>
  new Set(state.parts.flatMap((piece) => piece.nodes));
const drawnMarks = (state: FieldState) =>
  state.parts
    .flatMap((piece) =>
      piece.marks.map((mark) => `${mark.split(":")[0]}@${piece.beat}`),
    )
    .sort();

async function open(page: Page, path: string, width: number) {
  await page.setViewportSize({ width, height: width < 700 ? 844 : 900 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto(path);
  await page.evaluate(() => document.fonts.ready);
}

function expectSchematic(
  state: FieldState,
  id: string,
  orientation: "landscape" | "portrait",
) {
  const expected = inventory.schematics.find((s) => s.id === id)!;
  const where = `${id} ${orientation}`;
  expect(state.describedBy, where).toBe(expected.description);
  expect(
    state.labels.map(({ node, text, kind }) => ({ node, text, kind })),
    where,
  ).toEqual(
    expected.nodes.map(({ id: node, label, kind }) => ({
      node,
      text: label,
      kind,
    })),
  );
  // Exactly the connections the deployed drawing made — no fewer, and none
  // invented — including its return loop and its unnamed outputs.
  expect(drawnLinks(state), where).toEqual(
    [
      ...new Set(
        expected.flow[orientation].map((link) => `${link.from}>${link.to}`),
      ),
    ].sort(),
  );
  const nodes = drawnNodes(state);
  for (const node of expected.nodes)
    expect(nodes.has(node.id), `${where}: a piece stands for ${node.id}`).toBe(
      true,
    );
}

function expectScene(
  state: FieldState,
  id: string,
  orientation: "landscape" | "portrait",
) {
  const expected = inventory.scenes.find((s) => s.id === id)!;
  const where = `${id} ${orientation}`;
  expect(state.describedBy, where).toBe(expected.description);
  expect(
    state.labels.map(({ text, kind, beat }) => ({ text, kind, beat })),
    where,
  ).toEqual(expected[orientation].labels);
  expect(drawnMarks(state), where).toEqual(
    expected[orientation].marks
      .map((mark) => `${mark.kind}@${mark.beat}`)
      .sort(),
  );
  expect(drawnLinks(state), where).toEqual([...sceneLinks[id]].sort());
}

test("the fixture is the deployed drawings' inventory", () => {
  expect(inventory.source).toMatch(/^40e42eb/);
  expect(inventory.schematics.map((s) => s.id)).toEqual([
    "master",
    "training",
    "automation",
    "product",
  ]);
  expect(inventory.scenes.map((s) => s.id)).toEqual([
    "executives",
    "contributors",
    "builders",
    "review",
  ]);
});

test("the industry pages' drawing keeps its words and connections", async ({
  page,
}) => {
  await open(page, "/industries/private-equity/", 1440);
  expectSchematic(
    await page.locator(".page-drawing .system-field").evaluate(readField),
    "master",
    "portrait",
  );
});

test("each service drawing keeps its words and connections in both shapes", async ({
  page,
}) => {
  await open(page, "/", 1440);
  const services = [
    ["training", "Workshops"],
    ["automation", "Workflows"],
    ["product", "Automations"],
  ] as const;
  for (const [id, choice] of services) {
    const button = page.getByRole("button", { name: choice, exact: true });
    await button.click();
    await expect(button).toHaveAttribute("aria-pressed", "true");
    await expect
      .poll(() =>
        page
          .locator(".services-art .system-field")
          .evaluate((field) => field.getAttribute("aria-label")),
      )
      .toBe(inventory.schematics.find((s) => s.id === id)!.description);
    expectSchematic(
      await page.locator(".services-art .system-field").evaluate(readField),
      id,
      "landscape",
    );
    // Each article's own drawing is its portrait composition.
    expectSchematic(
      await page
        .locator(`#service-${id} .service-figure .system-field`)
        .evaluate(readField),
      id,
      "portrait",
    );
  }
  // And the same once a narrow layout has mounted them live.
  await open(page, "/", 390);
  for (const [id] of services)
    expectSchematic(
      await page
        .locator(`#service-${id} .service-figure .system-field`)
        .evaluate(readField),
      id,
      "portrait",
    );
});

test("each audience scene keeps its words, marks, beats and connections", async ({
  page,
}) => {
  for (const [width, orientation] of [
    [1440, "landscape"],
    [390, "portrait"],
  ] as const) {
    await open(page, "/", width);
    for (const id of ["executives", "contributors", "builders"]) {
      const panel = page.locator(`#audience-${id}`);
      expectScene(
        await panel.locator(".scene-field").evaluate(readField),
        id,
        orientation,
      );
      await expect(panel.locator(".audience-caption")).toHaveText(
        inventory.captions.find((c) => c.id === id)!.caption,
      );
    }
    await open(page, "/resources/", width);
    expectScene(
      await page.locator(".review-figure .scene-field").evaluate(readField),
      "review",
      orientation,
    );
  }
});

test("nothing draws itself, runs along a line, or loops", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);

  /**
   * Every animation a drawing starts, sampled while the opening drawing is
   * assembled, while a service drawing changes and while a scene is told. A
   * piece is placed — it may fade, move, turn or scale into its place — and
   * then it is still: no stroke is drawn on, nothing travels along a path,
   * nothing repeats.
   */
  const sample = () =>
    page.evaluate(() =>
      document
        .getAnimations()
        .filter((animation) => {
          const target = (animation.effect as KeyframeEffect | null)?.target;
          return !!target?.closest(".system-field");
        })
        .map((animation) => {
          const effect = animation.effect as KeyframeEffect;
          return {
            properties: [
              ...new Set(
                effect
                  .getKeyframes()
                  .flatMap((frame) => Object.keys(frame))
                  .filter(
                    (key) =>
                      ![
                        "offset",
                        "computedOffset",
                        "easing",
                        "composite",
                      ].includes(key),
                  ),
              ),
            ].sort(),
            iterations: effect.getTiming().iterations,
          };
        }),
    );

  const seen: Awaited<ReturnType<typeof sample>> = [];
  seen.push(...(await sample()));
  await page.waitForTimeout(300);
  seen.push(...(await sample()));

  await page.locator("#services").scrollIntoViewIfNeeded();
  await page.getByRole("button", { name: "Automations", exact: true }).click();
  await page.waitForTimeout(150);
  seen.push(...(await sample()));
  await page.waitForTimeout(350);
  seen.push(...(await sample()));

  await page.locator("#audiences").scrollIntoViewIfNeeded();
  await page.getByRole("button", { name: /AI builders/ }).click();
  await page.waitForTimeout(200);
  seen.push(...(await sample()));

  expect(seen.length, "the drawings were sampled mid-entrance").toBeGreaterThan(
    0,
  );
  for (const animation of seen) {
    expect(
      animation.properties.every((key) =>
        ["opacity", "transform"].includes(key),
      ),
      JSON.stringify(animation),
    ).toBe(true);
    expect(animation.iterations).toBe(1);
  }
  // Nor is anything built to travel: no moving signal, no SMIL.
  await expect(
    page.locator(
      ".system-field :is(.signal, .route, animate, animateMotion, animateTransform)",
    ),
  ).toHaveCount(0);
});

test("an assembled drawing rests exactly where a still one does", async ({
  page,
  context,
}) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);
  const still = await context.newPage();
  await still.setViewportSize({ width: 1440, height: 900 });
  await still.emulateMedia({ reducedMotion: "reduce" });
  await still.goto("/");
  await still.evaluate(() => document.fonts.ready);

  const read = (target: Page) =>
    target.locator(".services-art .system-field").evaluate(readField);
  await expect
    .poll(async () => {
      const state = await read(page);
      return { ...state.unsettled, animating: state.animating };
    })
    .toEqual({ parts: 0, words: 0, animating: 0 });
  expect(await read(page)).toEqual(await read(still));
  await still.close();
});

test("no drawing on any route is textured with dots, stripes or ruled lines", async ({
  page,
}) => {
  for (const route of [
    "/",
    "/services/",
    "/resources/",
    "/industries/private-equity/",
    "/industries/b2b-saas/",
    "/about/",
    "/blog/",
  ]) {
    await page.goto(route);
    await page.evaluate(() => document.fonts.ready);
    const textured = await page.evaluate(() => ({
      patterns: document.querySelectorAll("svg pattern").length,
      patternFills: [...document.querySelectorAll("svg [fill], svg [stroke]")]
        .map((el) => el.getAttribute("fill") ?? el.getAttribute("stroke") ?? "")
        .filter((value) => /url\(#/.test(value)).length,
      dashed: document.querySelectorAll(
        "svg [stroke-dasharray], svg [style*='stroke-dasharray']",
      ).length,
    }));
    expect(textured, route).toEqual({
      patterns: 0,
      patternFills: 0,
      dashed: 0,
    });
  }
});

test("the builder stair starts at Design and keeps its reviewed steps", async ({
  page,
}) => {
  await open(page, "/", 1440);
  const state = await page
    .locator("#audience-builders .scene-field")
    .evaluate(readField);
  expect(state.labels.map((label) => label.text)).toEqual([
    "A learner with a work problem",
    "Design",
    "Test",
    "Troubleshoot",
    "Anticipate failures",
    "Workflow in use",
  ]);
  // Design arrives before Test in the story, and each step carries a check.
  const beats = Object.fromEntries(
    state.labels.map((label) => [label.text, label.beat]),
  );
  expect(beats.Design).toBeLessThan(beats.Test);
  expect(
    drawnMarks(state).filter((mark) => mark.startsWith("check")),
  ).toHaveLength(4);
});

test("the executive scene reads as an illustrative Claude Daily Brief", async ({
  page,
}) => {
  await open(page, "/", 390);
  const panel = page.locator("#audience-executives");
  await expect(panel.getByRole("img")).toHaveAccessibleName(
    /Claude Daily Brief/,
  );
  const words = (await panel.locator(".system-label").allTextContents()).map(
    (text) => text.trim(),
  );
  for (const word of [
    "Claude Daily Brief",
    "Critical",
    "Needle Movers",
    "Calendar Intelligence",
    "Pipeline & Revenue",
    "Recommended Actions",
    "Executive direction",
    "Illustrative example · no live integrations",
  ])
    expect(words).toContain(word);
  await expect(panel.locator(".audience-caption")).toContainText(
    "not a live email, calendar or CRM integration",
  );
});

test("the Workshops drawing shows people designing, practising and reviewing", async ({
  page,
}) => {
  await open(page, "/", 390);
  const field = page.locator("#service-training .service-figure .system-field");
  await expect(field).toHaveAttribute(
    "aria-label",
    /whiteboard with sticky notes and a diagram.*keyboard practice.*group.*reusable skill/,
  );
  const state = await field.evaluate(readField);
  expect(state.parts.map((piece) => piece.name)).toEqual(
    expect.arrayContaining([
      "whiteboard",
      "designers",
      "desk",
      "review",
      "takeaway",
    ]),
  );
  expect(state.labels.map((label) => label.text)).toEqual([
    "Team's real work, designed at the whiteboard",
    "Live guided practice at the keyboard",
    "Group review",
    "Reusable skill",
    "Apply afterwards",
  ]);
});

test("the teams scene braids four role ribbons through a labelled human-review gate", async ({
  page,
}) => {
  await open(page, "/", 1440);
  const state = await page
    .locator("#audience-contributors .scene-field")
    .evaluate(readField);
  expect(state.parts.filter((piece) => piece.name === "role")).toHaveLength(4);
  expect(state.parts.map((piece) => piece.name)).toEqual(
    expect.arrayContaining(["crossings", "gate"]),
  );
  expect(state.labels.map((label) => label.text)).toContain(
    "Human in the loop",
  );
  await expect(
    page.locator("#audience-contributors .scene-field"),
  ).toHaveAttribute(
    "aria-label",
    /braided together and passing through the human-review gate/,
  );
});

test("the teams scene carries four separate paths past the gate to one shared result caption", async ({
  page,
}) => {
  const caption = "Reviewed work returns to each role.";
  for (const [path, width] of [
    ["/", 1440],
    ["/", 384],
    ["/services/", 1440],
  ] as const) {
    const where = `${path} at ${width}`;
    await open(page, path, width);
    await page
      .getByRole("button", { name: /Individual Contributors and Teams/ })
      .first()
      .click();
    const field = page.locator("#audience-contributors .scene-field");
    const state = await field.evaluate(readField);
    expect(
      state.labels.filter((label) => label.text === caption),
      `${where}: one caption`,
    ).toHaveLength(1);
    expect(
      state.parts.filter((piece) => piece.links.includes("human>result")),
      `${where}: four paths continue past the gate`,
    ).toHaveLength(4);
    await expect(field, where).toHaveAttribute(
      "aria-label",
      /reviewed work returns to each role/,
    );
    await expect(field.getByText(caption), where).toBeVisible();
  }
});

for (const [route, text] of [
  ["/", "100%"],
  ["/", "150%"],
  ["/services/", "100%"],
  ["/resources/", "100%"],
  ["/industries/private-equity/", "100%"],
] as const) {
  test(`drawing words fit on ${route} at ${text} text`, async ({ page }) => {
    await page.emulateMedia({ reducedMotion: "reduce" });
    const measure = () =>
      page.evaluate(async () => {
        await document.fonts.ready;
        const meet = (a: DOMRect, b: DOMRect) =>
          a.left < b.right - 1 &&
          b.left < a.right - 1 &&
          a.top < b.bottom - 1 &&
          b.top < a.bottom - 1;
        const problems: string[] = [];
        let drawings = 0;
        for (const field of document.querySelectorAll(".system-field")) {
          if (!(field as HTMLElement).offsetParent) continue;
          drawings += 1;
          const words = [...field.querySelectorAll(".system-label-text")].map(
            (el) => ({
              text: el.textContent?.trim() ?? "",
              box: el.getBoundingClientRect(),
            }),
          );
          words.forEach((a, i) => {
            if (a.box.left < -1 || a.box.right > innerWidth + 1)
              problems.push(`outside: ${a.text}`);
            for (const b of words.slice(i + 1))
              if (meet(a.box, b.box)) problems.push(`${a.text} / ${b.text}`);
          });
        }
        return {
          drawings,
          problems,
          scrolls: document.documentElement.scrollWidth > innerWidth,
        };
      });

    for (const width of [320, 384, 768, 1024, 1440]) {
      await page.setViewportSize({ width, height: 800 });
      await page.goto(route);
      await page.addStyleTag({ content: `html { font-size: ${text}; }` });
      // Every audience scene is told in turn, so each one is measured shown.
      const choices = page.locator("[data-audience]");
      const count = await choices.count();
      for (let index = 0; index < Math.max(count, 1); index += 1) {
        if (count) await choices.nth(index).click();
        const state = await measure();
        const where = `${route} at ${text}, ${width}px, audience ${index}`;
        expect(state.drawings, where).toBeGreaterThan(0);
        expect(state.problems, where).toEqual([]);
        expect(state.scrolls, where).toBe(false);
      }
    }
  });
}
