import { readFileSync } from "node:fs";
import { test, expect, type Page } from "@playwright/test";
import {
  readField,
  readTextFit,
  type FieldState,
  type TextFit,
} from "./drawing";

/**
 * The redesigned drawings keep everything the deployed ones said, except
 * where the September 29 review (issue #74) changed it on purpose.
 *
 * The fixture is an inventory of the drawings as deployed at the commit it
 * names, generated by `scripts/diagram-inventory.mjs` from that commit's own
 * modules: every word, its kind and its beat, every connection including the
 * feedback loops and the unlabelled branches, every mark on a person, a check
 * or a result, and each drawing's description and caption. The artwork was
 * redrawn from nothing; none of that was allowed to change. It was then
 * revised by hand, not regenerated, for the review's intentional changes: a
 * Design step before Test, an illustrative Claude Daily Brief for executives,
 * a whiteboard-to-keyboard Workshops drawing and the teams-and-contributors
 * name and gate. Issue #80 replaces the executive scene with four day cards.
 * Issue #139 redraws the Workflows drawing as an ordered process with named
 * decision and iteration annotations, and returns its portrait loop to the
 * design step rather than the brief.
 * Issue #140 lays the Automations drawing out as an ordered process ending in
 * a human approval.
 * PR #161 updates only the builder's accessible description to match the new
 * collaborative stations; its words, marks, beats and connections remain.
 * Issue #165 intentionally removes only the four contributor role-person marks
 * to match the one neutral human reviewer and absence of role figures.
 */

type Link = { from: string; to: string; weight: string };
type Inventory = {
  source: string;
  schematics: {
    id: string;
    description: string;
    nodes: { id: string; label: string; kind: string }[];
    annotations?: { key: string; text: string; kind: string }[];
    flow: Record<"landscape" | "portrait", Link[]>;
  }[];
  scenes: {
    id: string;
    description: string;
    landscape: Scene;
    portrait: Scene;
  }[];
  captions: { id: string; caption: string }[];
};
type Scene = {
  labels: { text: string; kind: string; beat: number }[];
  marks: { kind: string; beat: number }[];
};

const inventory = JSON.parse(
  readFileSync(
    new URL("./fixtures/diagram-inventory.json", import.meta.url),
    "utf8",
  ),
) as Inventory;

/**
 * The scenes' connections, read from the deployed drawings' routes: which
 * piece each route ran from and to. The executive day runs through four
 * cards with a final human decision; each role's skill answers to the human in the loop; the
 * builder's workflow is three linked parts; the review passes the three checks
 * in order before a person, then the business.
 */
const sceneLinks: Record<string, string[]> = {
  executives: [
    "brief>meeting",
    "meeting>debrief",
    "debrief>actions",
    "direction>actions",
  ],
  contributors: [
    ...[1, 2, 3, 4].flatMap((n) => [`role${n}>skill${n}`, `skill${n}>human`]),
    "human>result",
  ],
  builders: [
    "learner>design",
    "design>test",
    "test>troubleshoot",
    "troubleshoot>anticipate",
    "anticipate>workflow",
    "workflow>blocks",
  ],
  review: [
    "draft>weak",
    "weak>missing",
    "missing>false",
    "false>review",
    "review>business",
  ],
};

const drawnLinks = (state: FieldState) =>
  [...new Set(state.parts.flatMap((piece) => piece.links))].sort();
const drawnNodes = (state: FieldState) =>
  new Set(state.parts.flatMap((piece) => piece.nodes));
const drawnMarks = (state: FieldState) =>
  state.parts
    .flatMap((piece) =>
      piece.marks.map((mark) => `${mark.split(":")[0]}@${piece.beat}`),
    )
    .sort();

async function open(page: Page, path: string, width: number) {
  await page.setViewportSize({ width, height: width < 700 ? 844 : 900 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto(path);
  await page.evaluate(() => document.fonts.ready);
}

function expectSchematic(
  state: FieldState,
  id: string,
  orientation: "landscape" | "portrait",
) {
  const expected = inventory.schematics.find((s) => s.id === id)!;
  const where = `${id} ${orientation}`;
  expect(state.describedBy, where).toBe(expected.description);
  // The five node words, then any annotation words the drawing names its
  // decision and iteration with (issue #139 added them to Workflows).
  const expectedLabels = [
    ...expected.nodes.map(({ id: node, label, kind }) => ({
      node,
      text: label,
      kind,
    })),
    ...(expected.annotations ?? []).map(({ key: node, text, kind }) => ({
      node,
      text,
      kind,
    })),
  ];
  expect(
    state.labels.map(({ node, text, kind }) => ({ node, text, kind })),
    where,
  ).toEqual(expectedLabels);
  // Exactly the connections the deployed drawing made — no fewer, and none
  // invented — including its return loop and its unnamed outputs.
  expect(drawnLinks(state), where).toEqual(
    [
      ...new Set(
        expected.flow[orientation].map((link) => `${link.from}>${link.to}`),
      ),
    ].sort(),
  );
  const nodes = drawnNodes(state);
  for (const node of expected.nodes)
    expect(nodes.has(node.id), `${where}: a piece stands for ${node.id}`).toBe(
      true,
    );
}

function expectScene(
  state: FieldState,
  id: string,
  orientation: "landscape" | "portrait",
) {
  const expected = inventory.scenes.find((s) => s.id === id)!;
  const where = `${id} ${orientation}`;
  expect(state.describedBy, where).toBe(expected.description);
  expect(
    state.labels.map(({ text, kind, beat }) => ({ text, kind, beat })),
    where,
  ).toEqual(expected[orientation].labels);
  expect(drawnMarks(state), where).toEqual(
    expected[orientation].marks
      .map((mark) => `${mark.kind}@${mark.beat}`)
      .sort(),
  );
  expect(drawnLinks(state), where).toEqual([...sceneLinks[id]].sort());
}

test("the fixture is the deployed drawings' inventory", () => {
  expect(inventory.source).toMatch(/^40e42eb/);
  expect(inventory.schematics.map((s) => s.id)).toEqual([
    "master",
    "training",
    "automation",
    "product",
  ]);
  expect(inventory.scenes.map((s) => s.id)).toEqual([
    "executives",
    "contributors",
    "builders",
    "review",
  ]);
});

test("the industry pages' drawing keeps its words and connections", async ({
  page,
}) => {
  await open(page, "/industries/private-equity/", 1440);
  expectSchematic(
    await page.locator(".page-drawing .system-field").evaluate(readField),
    "master",
    "portrait",
  );
});

test("each service drawing keeps its words and connections in both shapes", async ({
  page,
}) => {
  await open(page, "/", 1440);
  const services = [
    ["training", "Workshops"],
    ["automation", "Workflows"],
    ["product", "Automations"],
  ] as const;
  for (const [id, choice] of services) {
    const button = page.getByRole("button", { name: choice, exact: true });
    await button.click();
    await expect(button).toHaveAttribute("aria-pressed", "true");
    await expect
      .poll(() =>
        page
          .locator(".services-art .system-field")
          .evaluate((field) => field.getAttribute("aria-label")),
      )
      .toBe(inventory.schematics.find((s) => s.id === id)!.description);
    expectSchematic(
      await page.locator(".services-art .system-field").evaluate(readField),
      id,
      "landscape",
    );
    // Each article's own drawing is its portrait composition.
    expectSchematic(
      await page
        .locator(`#service-${id} .service-figure .system-field`)
        .evaluate(readField),
      id,
      "portrait",
    );
  }
  // And the same once a narrow layout has mounted them live.
  await open(page, "/", 390);
  for (const [id] of services)
    expectSchematic(
      await page
        .locator(`#service-${id} .service-figure .system-field`)
        .evaluate(readField),
      id,
      "portrait",
    );
});

test("the Automation output branch stays clear of the direction and review words", async ({
  page,
}) => {
  for (const text of ["100%", "150%", "200%"]) {
    await open(page, "/", 1440);
    await page.evaluate((size) => {
      document.documentElement.style.fontSize = size;
    }, text);
    await page
      .getByRole("button", { name: "Automations", exact: true })
      .click();
    const field = page.locator(".services-art .system-field");
    await expect(
      field.getByText("Human direction", { exact: true }),
    ).toBeVisible();
    await expect(
      field.getByText("Human review", { exact: true }),
    ).toBeVisible();
    // Read the rendered path and text geometry, rather than pinning a path string.
    const collisions = await field.evaluate((element) => {
      const path = element.querySelector<SVGPathElement>(
        '[data-links~="human>out1"] path',
      )!;
      const transform = path.getScreenCTM()!;
      const labels = [
        ...element.querySelectorAll(
          '[data-node="human"] .system-label-text, [data-node="n3"] .system-label-text',
        ),
      ].map((label) => {
        const range = document.createRange();
        range.selectNodeContents(label);
        return { text: label.textContent, boxes: [...range.getClientRects()] };
      });
      const length = path.getTotalLength();
      const hits = new Set<string>();
      for (let distance = 0; distance <= length; distance += 0.5) {
        const point = path
          .getPointAtLength(distance)
          .matrixTransform(transform);
        for (const label of labels)
          if (
            label.boxes.some(
              (box) =>
                point.x >= box.left - 1 &&
                point.x <= box.right + 1 &&
                point.y >= box.top - 1 &&
                point.y <= box.bottom + 1,
            )
          )
            hits.add(label.text ?? "");
      }
      return [...hits];
    });
    expect(collisions, text).toEqual([]);
  }
});

test("the Workflows drawing reads as an ordered process with a labelled iteration", async ({
  page,
}) => {
  await open(page, "/", 1440);
  await page.getByRole("button", { name: "Workflows", exact: true }).click();
  const field = page.locator(".services-art .system-field");
  // The decision/review point and the iteration are named in visible words,
  // not left to arrow-decoding.
  await expect(
    field.getByText("Review point: does it still fit the work?", {
      exact: true,
    }),
  ).toBeVisible();
  await expect(
    field.getByText("Iteration back into tailored design and build", {
      exact: true,
    }),
  ).toBeVisible();
  // The accessible description carries the same order and iteration in words.
  await expect(field).toHaveAccessibleName(
    /brief.*tailored design and build.*test and review.*team deployment.*review in the customer context.*feeds back into tailored design and build/i,
  );
  // The landscape connectors read as the ordered chain 1→2→3→4→5: each step
  // leads to the next, and nothing gathers the first three into deployment.
  const chain = ["n1>n2", "n2>n3", "n3>human", "human>n4", "n4>n2"];
  await expect
    .poll(
      async () =>
        [
          ...new Set(
            (await field.evaluate(readField)).parts.flatMap(
              (piece) => piece.links,
            ),
          ),
        ].sort(),
      { timeout: 15_000 },
    )
    .toEqual([...chain].sort(), "landscape");
  // The portrait drawing returns to the design step, not the brief, and its
  // connectors read as the same ordered chain.
  await open(page, "/", 390);
  const portrait = page.locator(
    "#service-automation .service-figure .system-field",
  );
  await expect(
    portrait.getByText("Iteration back into tailored design and build", {
      exact: true,
    }),
  ).toBeVisible();
  await expect
    .poll(
      async () =>
        [
          ...new Set(
            (await portrait.evaluate(readField)).parts.flatMap(
              (piece) => piece.links,
            ),
          ),
        ].sort(),
      { timeout: 15_000 },
    )
    .toEqual([...chain].sort(), "portrait");
});

test("each audience scene keeps its words, marks, beats and connections", async ({
  page,
}) => {
  for (const [width, orientation] of [
    [1440, "landscape"],
    [390, "portrait"],
  ] as const) {
    await open(page, "/", width);
    for (const id of ["executives", "contributors", "builders"]) {
      const panel = page.locator(`#audience-${id}`);
      expectScene(
        await panel.locator(".scene-field").evaluate(readField),
        id,
        "portrait",
      );
      await expect(panel.locator(".audience-caption")).toHaveText(
        inventory.captions.find((c) => c.id === id)!.caption,
      );
    }
    await open(page, "/resources/", width);
    expectScene(
      await page.locator(".review-figure .scene-field").evaluate(readField),
      "review",
      orientation,
    );
  }
});

test("nothing draws itself, runs along a line, or loops", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);

  /**
   * Every animation a drawing starts, sampled while the opening drawing is
   * assembled, while a service drawing changes and while a scene is told. A
   * piece is placed — it may fade, move, turn or scale into its place — and
   * then it is still: no stroke is drawn on, nothing travels along a path,
   * nothing repeats.
   */
  const sample = () =>
    page.evaluate(() =>
      document
        .getAnimations()
        .filter((animation) => {
          const target = (animation.effect as KeyframeEffect | null)?.target;
          return !!target?.closest(".system-field");
        })
        .map((animation) => {
          const effect = animation.effect as KeyframeEffect;
          return {
            properties: [
              ...new Set(
                effect
                  .getKeyframes()
                  .flatMap((frame) => Object.keys(frame))
                  .filter(
                    (key) =>
                      ![
                        "offset",
                        "computedOffset",
                        "easing",
                        "composite",
                      ].includes(key),
                  ),
              ),
            ].sort(),
            iterations: effect.getTiming().iterations,
          };
        }),
    );

  const seen: Awaited<ReturnType<typeof sample>> = [];
  seen.push(...(await sample()));
  await page.waitForTimeout(300);
  seen.push(...(await sample()));

  await page.locator("#services").scrollIntoViewIfNeeded();
  await page.getByRole("button", { name: "Automations", exact: true }).click();
  await page.waitForTimeout(150);
  seen.push(...(await sample()));
  await page.waitForTimeout(350);
  seen.push(...(await sample()));

  await page.locator("#audiences").scrollIntoViewIfNeeded();
  await page.getByRole("button", { name: /AI builders/ }).click();
  await page.waitForTimeout(200);
  seen.push(...(await sample()));

  expect(seen.length, "the drawings were sampled mid-entrance").toBeGreaterThan(
    0,
  );
  for (const animation of seen) {
    expect(
      animation.properties.every((key) =>
        ["opacity", "transform"].includes(key),
      ),
      JSON.stringify(animation),
    ).toBe(true);
    expect(animation.iterations).toBe(1);
  }
  // Nor is anything built to travel: no moving signal, no SMIL.
  await expect(
    page.locator(
      ".system-field :is(.signal, .route, animate, animateMotion, animateTransform)",
    ),
  ).toHaveCount(0);
});

test("an assembled drawing rests exactly where a still one does", async ({
  page,
  context,
}) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);
  const still = await context.newPage();
  await still.setViewportSize({ width: 1440, height: 900 });
  await still.emulateMedia({ reducedMotion: "reduce" });
  await still.goto("/");
  await still.evaluate(() => document.fonts.ready);

  const read = (target: Page) =>
    target.locator(".services-art .system-field").evaluate(readField);
  await expect
    .poll(async () => {
      const state = await read(page);
      return { ...state.unsettled, animating: state.animating };
    })
    .toEqual({ parts: 0, words: 0, animating: 0 });
  expect(await read(page)).toEqual(await read(still));
  await still.close();
});

test("no drawing on any route is textured with dots, stripes or ruled lines", async ({
  page,
}) => {
  for (const route of [
    "/",
    "/services/",
    "/resources/",
    "/industries/private-equity/",
    "/industries/portfolio-companies/",
    "/industries/b2b-saas/",
    "/about/",
    "/blog/",
  ]) {
    await page.goto(route);
    await page.evaluate(() => document.fonts.ready);
    const textured = await page.evaluate(() => ({
      patterns: document.querySelectorAll("svg pattern").length,
      patternFills: [...document.querySelectorAll("svg [fill], svg [stroke]")]
        .map((el) => el.getAttribute("fill") ?? el.getAttribute("stroke") ?? "")
        .filter((value) => /url\(#/.test(value)).length,
      dashed: document.querySelectorAll(
        "svg [stroke-dasharray], svg [style*='stroke-dasharray']",
      ).length,
    }));
    expect(textured, route).toEqual({
      patterns: 0,
      patternFills: 0,
      dashed: 0,
    });
  }
});

test("the builder stations start at Design and keep their reviewed steps", async ({
  page,
}) => {
  await open(page, "/", 1440);
  const state = await page
    .locator("#audience-builders .scene-field")
    .evaluate(readField);
  expect(state.labels.map((label) => label.text)).toEqual([
    "A learner with a work problem",
    "Design",
    "Test",
    "Troubleshoot",
    "Anticipate failures",
    "Workflow in use",
  ]);
  // Design arrives before Test in the story, and each step carries a check.
  const beats = Object.fromEntries(
    state.labels.map((label) => [label.text, label.beat]),
  );
  expect(beats.Design).toBeLessThan(beats.Test);
  expect(
    drawnMarks(state).filter((mark) => mark.startsWith("check")),
  ).toHaveLength(4);
  expect(state.describedBy).toMatch(
    /works with colleagues through four reviewed stations.*design, test, troubleshoot, anticipate failures.*three joined parts/i,
  );
  expect(state.describedBy).not.toMatch(/climb|stair/i);
});

test("the executive day names four ordered cards and keeps the decision illustrative", async ({
  page,
}) => {
  const labels = [
    "Claude Daily Brief",
    "Meeting Brief",
    "Meeting Debrief",
    "Actions from Transcripts",
  ];
  // Each card carries a short fictional sample of what it produces: the two
  // briefs prepare, the debrief follows up, the last card acts on transcripts.
  const samples = [
    "Sample: 3 priorities",
    "Sample: agenda draft",
    "Sample: owners, dates",
    "Sample: tasks from notes",
  ];
  for (const route of ["/", "/services/"]) {
    for (const width of [1440, 384]) {
      await open(page, route, width);
      const panel = page.locator("#audience-executives");
      const field = panel.locator(".scene-field");
      const words = await field.locator(".system-label").allTextContents();
      expect(
        words
          .filter((word) => labels.includes(word.trim()))
          .map((word) => word.trim()),
      ).toEqual(labels);
      for (const sample of samples)
        await expect(field.getByText(sample, { exact: true })).toHaveCount(1);
      // The samples read as preparation, follow-up and transcript actions,
      // and every one is marked as a sample rather than real output.
      await expect(field.getByText(/3 priorities/)).toBeVisible();
      await expect(field.getByText(/agenda draft/)).toBeVisible();
      await expect(field.getByText(/owners, dates/)).toBeVisible();
      await expect(field.getByText(/tasks from notes/)).toBeVisible();
      await expect(field.getByText("You decide", { exact: true })).toHaveCount(
        1,
      );
      for (const removed of [
        "Your operating problem",
        "Tailored executive skill",
        "Executive direction",
      ])
        await expect(field.getByText(removed, { exact: true })).toHaveCount(0);
      await expect(field).toHaveAccessibleName(
        /Claude Daily Brief.*Meeting Brief.*Meeting Debrief.*Actions from Transcripts.*You decide.*illustrative.*no live calendar, email, CRM or transcript integration/i,
      );
      await expect(panel.locator(".audience-caption")).toContainText(
        "Claude Daily Brief → Meeting Brief → Meeting Debrief → Actions from Transcripts",
      );
      await expect(panel.locator(".audience-caption")).toContainText(
        "no live calendar, email, CRM or transcript integration",
      );
    }
  }
});

test("executive documents explain their recognizable output formats", async ({
  page,
}) => {
  for (const width of [1440, 390]) {
    await open(page, "/", width);
    const field = page.locator("#audience-executives .scene-field");
    await expect(field).toHaveAccessibleName(
      /Daily Brief with three ranked priorities.*Meeting Brief with an agenda.*Meeting Debrief with owner and date columns.*Actions from Transcripts with notes feeding a task checklist.*You decide.*illustrative.*no live calendar, email, CRM or transcript integration/i,
    );
  }
});

test("executive timeline words stay whole and separate with enlarged text", async ({
  page,
}) => {
  for (const width of [384, 1024, 1440]) {
    await page.setViewportSize({ width, height: 742 });
    await page.goto("/");
    await page.evaluate(() => {
      document.documentElement.style.fontSize = "200%";
    });
    expect(
      await page
        .locator("html")
        .evaluate((html) => getComputedStyle(html).fontSize),
    ).toBe("32px");
    await page.evaluate(() => document.fonts.ready);
    await page.getByRole("button", { name: /C-level executives/ }).click();
    const fields = page.locator(
      '.audience-art [data-audience-scene="0"] .scene-field:visible, #audience-executives .scene-field:visible',
    );
    await expect(fields).toHaveCount(1);
    await fields.first().scrollIntoViewIfNeeded();
    await expect
      .poll(
        async () => {
          const field = fields.first();
          const state = await field.evaluate(readField);
          const fit = await field.evaluate(readTextFit);
          return {
            animating: state.animating,
            unsettled: state.unsettled,
            problems: wordProblems(fit),
            decisionOnCard: fit.find((label) => label.text === "You decide")
              ?.onCard,
          };
        },
        { timeout: 20000 },
      )
      .toEqual({
        animating: 0,
        unsettled: { parts: 0, words: 0 },
        problems: [],
        decisionOnCard: true,
      });
    await expect
      .poll(() =>
        fields.first().evaluate((field) => {
          const caption = field
            .querySelector('[data-node="illustrative"] .system-label-text')!
            .getBoundingClientRect();
          const box = field.getBoundingClientRect();
          return caption.top >= box.top && caption.bottom <= box.bottom;
        }),
      )
      .toBe(true);
    const overlaps = await fields.first().evaluate((field) => {
      const boxes = [...field.querySelectorAll(".system-label-text")].map(
        (label) => ({
          text: label.textContent,
          box: label.getBoundingClientRect(),
        }),
      );
      return boxes.flatMap((a, i) =>
        boxes
          .slice(i + 1)
          .filter(
            (b) =>
              a.box.left < b.box.right - 1 &&
              b.box.left < a.box.right - 1 &&
              a.box.top < b.box.bottom - 1 &&
              b.box.top < a.box.bottom - 1,
          )
          .map((b) => `${a.text} / ${b.text}`),
      );
    });
    expect(overlaps).toEqual([]);
  }
});

test("each executive sample sits inside its own card with enlarged text", async ({
  page,
}) => {
  const cards: [string, string][] = [
    ["brief", "Sample: 3 priorities"],
    ["meeting", "Sample: agenda draft"],
    ["debrief", "Sample: owners, dates"],
    ["actions", "Sample: tasks from notes"],
  ];
  const outside = (field: Element, pairs: [string, string][]) =>
    pairs.flatMap(([key, text]) => {
      const card = field
        .querySelector(`[data-nodes~="${key}"] rect.f-paper`)!
        .getBoundingClientRect();
      const sample = field
        .querySelector(`[data-node="${key}-sample"] .system-label-text`)!
        .getBoundingClientRect();
      return sample.left >= card.left - 1 &&
        sample.right <= card.right + 1 &&
        sample.top >= card.top - 1 &&
        sample.bottom <= card.bottom + 1
        ? []
        : [`"${text}" is outside its card`];
    });
  for (const width of [384, 1024, 1440]) {
    await page.setViewportSize({ width, height: 742 });
    await page.goto("/");
    await page.evaluate(() => {
      document.documentElement.style.fontSize = "200%";
    });
    await page.evaluate(() => document.fonts.ready);
    await page.getByRole("button", { name: /C-level executives/ }).click();
    const fields = page.locator(
      '.audience-art [data-audience-scene="0"] .scene-field:visible, #audience-executives .scene-field:visible',
    );
    await expect(fields).toHaveCount(1);
    await fields.first().scrollIntoViewIfNeeded();
    for (const [, text] of cards)
      await expect(
        fields.first().getByText(text, { exact: true }),
      ).toBeVisible();
    await expect
      .poll(() => fields.first().evaluate(outside, cards))
      .toEqual([]);
  }
});

for (const [width, height] of [
  [384, 686],
  [384, 742],
] as const) {
  test(`the executive timeline is complete without scripting at ${width}×${height} [production]`, async ({
    browser,
  }) => {
    const context = await browser.newContext({
      javaScriptEnabled: false,
      viewport: { width, height },
    });
    const page = await context.newPage();
    await page.goto("http://127.0.0.1:4179/website-redesign/");
    const field = page.locator("#audience-executives .scene-field:visible");
    for (const text of [
      "Claude Daily Brief",
      "Sample: 3 priorities",
      "Meeting Brief",
      "Sample: agenda draft",
      "Meeting Debrief",
      "Sample: owners, dates",
      "Actions from Transcripts",
      "Sample: tasks from notes",
      "You decide",
    ])
      await expect(field.getByText(text, { exact: true })).toBeVisible();
    await expect
      .poll(() => page.evaluate(() => document.fonts.status))
      .toBe("loaded");
    const fit = await field.evaluate(readTextFit);
    expect(wordProblems(fit)).toEqual([]);
    for (const label of fit)
      expect(label.fontSize, label.text).toBeGreaterThanOrEqual(13);
    // Each sample sits inside the card it illustrates, without scripting too.
    expect(
      await field.evaluate((element) => {
        const pairs = [
          ["brief", "Sample: 3 priorities"],
          ["meeting", "Sample: agenda draft"],
          ["debrief", "Sample: owners, dates"],
          ["actions", "Sample: tasks from notes"],
        ];
        return pairs.flatMap(([key, text]) => {
          const card = element
            .querySelector(`[data-nodes~="${key}"] rect.f-paper`)!
            .getBoundingClientRect();
          const sample = element
            .querySelector(`[data-node="${key}-sample"] .system-label-text`)!
            .getBoundingClientRect();
          return sample.left >= card.left - 1 &&
            sample.right <= card.right + 1 &&
            sample.top >= card.top - 1 &&
            sample.bottom <= card.bottom + 1
            ? []
            : [`"${text}" is outside its card`];
        });
      }),
    ).toEqual([]);
    expect(
      await field.evaluate((element) => element.getBoundingClientRect().width),
    ).toBeGreaterThan(300);
    expect(
      await page.evaluate(
        () => document.documentElement.scrollWidth <= innerWidth,
      ),
    ).toBe(true);
    await context.close();
  });
}

test("the Workshops drawing shows people designing, practising and reviewing", async ({
  page,
}) => {
  await open(page, "/", 390);
  const field = page.locator("#service-training .service-figure .system-field");
  await expect(field).toHaveAttribute(
    "aria-label",
    /whiteboard with sticky notes and a diagram.*keyboard practice.*group.*reusable skill/,
  );
  const state = await field.evaluate(readField);
  expect(state.parts.map((piece) => piece.name)).toEqual(
    expect.arrayContaining([
      "whiteboard",
      "designers",
      "desk",
      "review",
      "takeaway",
    ]),
  );
  expect(state.labels.map((label) => label.text)).toEqual([
    "Team's real work, designed at the whiteboard",
    "Live guided practice at the keyboard",
    "Group review",
    "Reusable skill",
    "Apply afterwards",
  ]);
});

test("the Automations drawing reads as an ordered process with a human approval", async ({
  page,
}) => {
  for (const [width, selector] of [
    [1440, ".services-art .system-field"],
    [390, "#service-product .service-figure .system-field"],
  ] as const) {
    const where = `product at ${width}`;
    await open(page, "/", width);
    if (width === 1440)
      await page
        .getByRole("button", { name: "Automations", exact: true })
        .click();
    const field = page.locator(selector);
    await expect(field, where).toHaveAttribute(
      "aria-label",
      /moves through system handoffs in order.*human review marks approval.*usable output/,
    );
    const state = await field.evaluate(readField);
    // The five words arrive in the order the work moves through them.
    expect(
      state.labels.map((label) => label.text),
      where,
    ).toEqual([
      "Repetitive work",
      "System handoffs",
      "Human direction",
      "Human review",
      "Usable output",
    ]);
    const order = ["n1", "n2", "human", "n3", "n4"].map(
      (node) => state.labels.find((label) => label.node === node)!.beat,
    );
    expect(order, `${where}: each step arrives after the one before`).toEqual(
      [...order].sort((a, b) => a - b),
    );
    expect(new Set(order).size, `${where}: no two steps share a beat`).toBe(5);
    const links = new Set(state.parts.flatMap((piece) => piece.links));
    for (const link of ["n1>n2", "n2>human", "human>n3", "n3>n4"])
      expect(links.has(link), `${where}: the drawing joins ${link}`).toBe(true);
    // The decision is a person's seal on the review step, not an auto-pass.
    expect(
      state.parts.flatMap((piece) => piece.marks),
      `${where}: the review step carries the approval seal`,
    ).toContain("seal:approved");
  }
});

test("the teams scene runs four separate role lanes through a labelled human-review gate", async ({
  page,
}) => {
  await open(page, "/", 1440);
  const state = await page
    .locator("#audience-contributors .scene-field")
    .evaluate(readField);
  expect(state.parts.filter((piece) => piece.name === "role")).toHaveLength(4);
  expect(state.parts.map((piece) => piece.name)).toEqual(
    expect.arrayContaining(["lanes", "gate"]),
  );
  expect(state.labels.map((label) => label.text)).toContain(
    "Human in the loop",
  );
  await expect(
    page.locator("#audience-contributors .scene-field"),
  ).toHaveAttribute(
    "aria-label",
    /each running its own lane to the human-review gate/,
  );
});

test("the contributor workflows use one neutral reviewer icon and no role figures", async ({
  page,
}) => {
  for (const width of [628, 1920]) {
    await open(page, "/", width);
    await page.emulateMedia({
      reducedMotion: width === 1920 ? "no-preference" : "reduce",
    });
    await page.goto("/");
    await page
      .getByRole("button", { name: /Individual Contributors and Teams/ })
      .first()
      .click();
    const field = page.locator(
      width === 1920
        ? '.audience-art [data-audience-scene="1"] .scene-field'
        : "#audience-contributors .scene-field",
    );
    await expect(field).toBeVisible();
    await expect
      .poll(async () => (await field.evaluate(readField)).animating)
      .toBe(0);
    await expect(field.locator('[data-part="role"] circle')).toHaveCount(0);
    await expect(field.locator('[data-part="role"] ellipse')).toHaveCount(0);
    await expect(
      field.locator('[data-part="human-reviewer"] circle'),
    ).toHaveCount(1);
    await expect(
      field.locator('[data-part="human-reviewer"] path'),
    ).toHaveCount(1);
    await expect(
      field.getByText("Human in the loop", { exact: true }),
    ).toBeVisible();
    const state = await field.evaluate(readField);
    expect(
      state.parts
        .flatMap((piece) => piece.marks)
        .filter((mark) => mark.startsWith("person:")),
    ).toEqual([]);
    expect(
      state.parts.filter((piece) =>
        piece.links.some((link) => link.endsWith(">human")),
      ),
    ).toHaveLength(4);
  }
});

test("contributor function labels have open space without enclosing bars", async ({
  page,
}) => {
  for (const width of [628, 1920]) {
    await open(page, "/", width);
    await page.emulateMedia({
      reducedMotion: width === 1920 ? "no-preference" : "reduce",
    });
    await page.goto("/");
    await page
      .getByRole("button", { name: /Individual Contributors and Teams/ })
      .first()
      .click();
    const field = page.locator(
      width === 1920
        ? '.audience-art [data-audience-scene="1"] .scene-field'
        : "#audience-contributors .scene-field",
    );
    await expect(field).toBeVisible();
    await expect
      .poll(async () => (await field.evaluate(readField)).animating)
      .toBe(0);
    const enclosingBars = await field.evaluate((root) => {
      const labels = [
        ...root.querySelectorAll('[data-node^="skill"] .system-label-text'),
      ];
      return labels.flatMap((label) => {
        const words = label.getBoundingClientRect();
        return [...root.querySelectorAll('[data-part="role"] rect')]
          .filter((shape) => {
            const box = shape.getBoundingClientRect();
            return (
              box.left <= words.left &&
              box.right >= words.right &&
              box.top <= words.top &&
              box.bottom >= words.bottom
            );
          })
          .map(() => label.textContent);
      });
    });
    expect(enclosingBars, `${width}px: functions read as plain labels`).toEqual(
      [],
    );
    for (const text of [
      "Deal screening",
      "Plans and reviews",
      "Feedback triage",
      "Account planning",
    ])
      await expect(field.getByText(text, { exact: true })).toBeVisible();
  }
});

test("the teams scene keeps each role lane clear of the others into and out of the gate", async ({
  page,
}) => {
  const clearanceOf = (root: Element) => {
    const lanes = [...root.querySelectorAll(".part")]
      .filter(
        (piece) =>
          piece.getAttribute("data-part") === "role" ||
          piece.getAttribute("data-part") === "return",
      )
      .map((piece) => {
        const line = [...piece.querySelectorAll("path")].find(
          (el) =>
            el.getAttribute("fill") === "none" &&
            (el.getAttribute("stroke") ?? "").startsWith("var("),
        )! as unknown as SVGPathElement;
        const half = Number(line.getAttribute("stroke-width")) / 2;
        const length = line.getTotalLength();
        const samples: { x: number; y: number }[] = [];
        const count = 120;
        for (let i = 0; i <= count; i += 1) {
          const at = line.getPointAtLength((length * i) / count);
          samples.push({ x: at.x, y: at.y });
        }
        return { samples, half };
      });
    let pair = "";
    let distance = Infinity;
    for (let a = 0; a < lanes.length; a += 1)
      for (let b = a + 1; b < lanes.length; b += 1) {
        let near = Infinity;
        for (const p of lanes[a].samples)
          for (const q of lanes[b].samples)
            near = Math.min(near, Math.hypot(p.x - q.x, p.y - q.y));
        if (near < distance) {
          distance = near;
          pair = `${a}/${b}`;
        }
      }
    const allowance = Math.max(
      ...lanes.flatMap((lane, i) =>
        lanes.slice(i + 1).map((other) => lane.half + other.half),
      ),
    );
    return { pair, distance, allowance, lanes: lanes.length };
  };
  const expectClear = (
    clearance: {
      pair: string;
      distance: number;
      allowance: number;
      lanes: number;
    },
    where: string,
  ) => {
    expect(clearance.lanes, `${where}: four lanes in, four out`).toBe(8);
    expect(
      clearance.distance,
      `${where}: closest lanes ${clearance.pair} stay a ribbon apart`,
    ).toBeGreaterThanOrEqual(clearance.allowance - 1);
  };
  // Portrait: what a narrow or reduced-motion visitor reads in the article.
  await open(page, "/", 384);
  await page
    .getByRole("button", { name: /Individual Contributors and Teams/ })
    .first()
    .click();
  expectClear(
    await page
      .locator("#audience-contributors .scene-field")
      .evaluate(clearanceOf),
    "portrait at 384px",
  );
  // Landscape: the pinned scene on a wide screen with motion allowed.
  await page.setViewportSize({ width: 1638, height: 900 });
  await page.emulateMedia({ reducedMotion: "no-preference" });
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);
  await page
    .getByRole("button", { name: /Individual Contributors and Teams/ })
    .first()
    .click();
  const wide = page.locator(
    '.audience-art [data-audience-scene="1"] .scene-field',
  );
  await wide.scrollIntoViewIfNeeded();
  await expect
    .poll(async () => (await wide.evaluate(readField)).animating, {
      timeout: 20000,
    })
    .toBe(0);
  expectClear(await wide.evaluate(clearanceOf), "landscape at 1638px");
});

/** What the teams gate's rects look like from the browser, in viewBox units. */
const gateFrameOf = (root: Element) => {
  const svg = root.querySelector("svg")!;
  const viewHeight = Number(svg.getAttribute("viewBox")!.split(" ")[3]);
  const gate = [...root.querySelectorAll(".part")].find(
    (piece) => piece.getAttribute("data-part") === "gate",
  )!;
  const rects = [...gate.querySelectorAll("rect")].map((rect) => ({
    y: Number(rect.getAttribute("y")),
    height: Number(rect.getAttribute("height")),
  }));
  return {
    count: rects.length,
    thinnest: Math.min(...rects.map((rect) => rect.height)),
    frameTall: rects.filter((rect) => rect.height > viewHeight * 0.5).length,
    pastFrame: rects.filter((rect) => rect.y + rect.height > viewHeight + 1)
      .length,
  };
};

const expectGateFrame = (
  frame: {
    count: number;
    thinnest: number;
    frameTall: number;
    pastFrame: number;
  },
  where: string,
) => {
  expect(frame.count, `${where}: four posts plus the label plate`).toBe(6);
  expect(frame.thinnest, `${where}: posts are thin`).toBeLessThan(40);
  // The wide composition's side posts span the frame; the narrow one's are
  // transposed, so at most two rects may be frame-height.
  expect(
    frame.frameTall,
    `${where}: no third frame-height rect`,
  ).toBeLessThanOrEqual(2);
  expect(frame.pastFrame, `${where}: no rect leaves the drawing`).toBe(0);
};

test("the teams gate is a frame of posts, not a filled block", async ({
  page,
}) => {
  // Regression: the gate's bottom post once rendered with the frame's full
  // height, painting a dark bar past the canvas edge (review finding on the
  // October redraw). No gate rect may be frame-height or leave the drawing.
  // Portrait: what a narrow or reduced-motion visitor reads in the article.
  await open(page, "/", 384);
  await page
    .getByRole("button", { name: /Individual Contributors and Teams/ })
    .first()
    .click();
  await expectGateFrame(
    await page
      .locator("#audience-contributors .scene-field")
      .evaluate(gateFrameOf),
    "portrait at 384px",
  );
  // Landscape: the pinned scene on a wide screen with motion allowed.
  await page.setViewportSize({ width: 1638, height: 900 });
  await page.emulateMedia({ reducedMotion: "no-preference" });
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);
  await page
    .getByRole("button", { name: /Individual Contributors and Teams/ })
    .first()
    .click();
  const wide = page.locator(
    '.audience-art [data-audience-scene="1"] .scene-field',
  );
  await wide.scrollIntoViewIfNeeded();
  await expect
    .poll(async () => (await wide.evaluate(readField)).animating, {
      timeout: 20000,
    })
    .toBe(0);
  await expectGateFrame(
    await wide.evaluate(gateFrameOf),
    "landscape at 1638px",
  );
});

test("the teams scene carries four separate paths past the gate to one shared result caption", async ({
  page,
}) => {
  const caption = "Reviewed work returns to each role.";
  for (const [path, width] of [
    ["/", 1440],
    ["/", 384],
    ["/services/", 1440],
  ] as const) {
    const where = `${path} at ${width}`;
    await open(page, path, width);
    await page
      .getByRole("button", { name: /Individual Contributors and Teams/ })
      .first()
      .click();
    const field = page.locator("#audience-contributors .scene-field");
    const state = await field.evaluate(readField);
    expect(
      state.labels.filter((label) => label.text === caption),
      `${where}: one caption`,
    ).toHaveLength(1);
    expect(
      state.parts.filter((piece) => piece.links.includes("human>result")),
      `${where}: four paths continue past the gate`,
    ).toHaveLength(4);
    await expect(field, where).toHaveAttribute(
      "aria-label",
      /reviewed work returns to each role/,
    );
    await expect(field.getByText(caption), where).toBeVisible();
  }
});

for (const [route, text] of [
  ["/", "100%"],
  ["/", "150%"],
  ["/services/", "100%"],
  ["/resources/", "100%"],
  ["/industries/private-equity/", "100%"],
] as const) {
  test(`drawing words fit on ${route} at ${text} text`, async ({ page }) => {
    await page.emulateMedia({ reducedMotion: "reduce" });
    const measure = () =>
      page.evaluate(async () => {
        await document.fonts.ready;
        const meet = (a: DOMRect, b: DOMRect) =>
          a.left < b.right - 1 &&
          b.left < a.right - 1 &&
          a.top < b.bottom - 1 &&
          b.top < a.bottom - 1;
        const problems: string[] = [];
        let drawings = 0;
        for (const field of document.querySelectorAll(".system-field")) {
          if (!(field as HTMLElement).offsetParent) continue;
          drawings += 1;
          const words = [...field.querySelectorAll(".system-label-text")].map(
            (el) => ({
              text: el.textContent?.trim() ?? "",
              box: el.getBoundingClientRect(),
            }),
          );
          words.forEach((a, i) => {
            if (a.box.left < -1 || a.box.right > innerWidth + 1)
              problems.push(`outside: ${a.text}`);
            for (const b of words.slice(i + 1))
              if (meet(a.box, b.box)) problems.push(`${a.text} / ${b.text}`);
          });
        }
        return {
          drawings,
          problems,
          scrolls: document.documentElement.scrollWidth > innerWidth,
        };
      });

    for (const width of [320, 384, 768, 1024, 1440]) {
      await page.setViewportSize({ width, height: 800 });
      await page.goto(route);
      await page.addStyleTag({ content: `html { font-size: ${text}; }` });
      // Every audience scene is told in turn, so each one is measured shown.
      const choices = page.locator("[data-audience]");
      const count = await choices.count();
      for (let index = 0; index < Math.max(count, 1); index += 1) {
        if (count) await choices.nth(index).click();
        const state = await measure();
        const where = `${route} at ${text}, ${width}px, audience ${index}`;
        expect(state.drawings, where).toBeGreaterThan(0);
        expect(state.problems, where).toEqual([]);
        expect(state.scrolls, where).toBe(false);
      }
    }
  });
}

/**
 * What a person reads in the contributors scene: no word is broken inside
 * itself. Role tabs, the gate's plate and the result keep their labels;
 * function labels read in open space without enclosing bars (#166). The review of
 * issue #78 found both failing while the overlap test above passed.
 */
const wordProblems = (fit: TextFit) =>
  fit.flatMap((label) => [
    ...label.splitWords.map((word) => `"${word}" is split in "${label.text}"`),
    ...(label.outsideCard ? [`"${label.text}" overflows its card`] : []),
    ...(label.onCard === false ? [`"${label.text}" has no card`] : []),
    ...(label.outsideViewport ? [`"${label.text}" is off screen`] : []),
  ]);

for (const [route, width, text] of [
  ["/", 384, "150%"],
  ["/", 384, "100%"],
  ["/", 628, "150%"],
  ["/", 768, "150%"],
  ["/", 860, "150%"],
  ["/", 861, "150%"],
  ["/", 900, "150%"],
  ["/", 1024, "150%"],
  ["/", 320, "100%"],
  ["/", 1440, "150%"],
  ["/services/", 384, "150%"],
] as const) {
  test(`teams scene words stay whole with open function labels on ${route} at ${width}px with ${text} text applied at load`, async ({
    page,
  }) => {
    await page.emulateMedia({ reducedMotion: "reduce" });
    // The setting is in place before the scene is first drawn.
    await page.addInitScript((size) => {
      const apply = () => {
        if (!document.documentElement) return false;
        document.documentElement.style.fontSize = size;
        return true;
      };
      if (!apply())
        new MutationObserver((_, watch) => {
          if (apply()) watch.disconnect();
        }).observe(document, { childList: true });
    }, text);
    await page.setViewportSize({ width, height: 742 });
    await page.goto(route);
    await page.evaluate(() => document.fonts.ready);
    await page
      .getByRole("button", { name: /Individual Contributors and Teams/ })
      .first()
      .click();
    const field = page.locator("#audience-contributors .scene-field");
    await expect(
      field.getByText("Reviewed work returns to each role."),
    ).toBeVisible();
    const fit = await field.evaluate(readTextFit, [
      "skill1",
      "skill2",
      "skill3",
      "skill4",
    ]);
    expect(fit.map((label) => label.text)).toEqual(
      expect.arrayContaining([
        "Feedback triage",
        "Account planning",
        "Human in the loop",
        "Reviewed work returns to each role.",
      ]),
    );
    expect(wordProblems(fit)).toEqual([]);
  });
}

/**
 * What a person reads in the builders scene's article figure: no stage label
 * is broken inside itself, every label stays on screen and legible, and none
 * cover another (issue #138 — "Troubleshoot" split midword in its step).
 * Under reduced motion (and on narrow screens) the article's portrait figure
 * is the composition shown, so this guards phone widths and enlarged text.
 */
for (const [width, text] of [
  [320, "100%"],
  [384, "100%"],
  [384, "150%"],
  [768, "100%"],
  [768, "150%"],
  [1024, "100%"],
  [1024, "150%"],
  [1440, "100%"],
  [1440, "150%"],
] as const) {
  test(`builder stair words stay whole at ${width}px with ${text} text applied at load`, async ({
    page,
  }) => {
    await page.emulateMedia({ reducedMotion: "reduce" });
    // The setting is in place before the scene is first drawn.
    await page.addInitScript((size) => {
      const apply = () => {
        if (!document.documentElement) return false;
        document.documentElement.style.fontSize = size;
        return true;
      };
      if (!apply())
        new MutationObserver((_, watch) => {
          if (apply()) watch.disconnect();
        }).observe(document, { childList: true });
    }, text);
    await page.setViewportSize({ width, height: 742 });
    await page.goto("/");
    await page.evaluate(() => document.fonts.ready);
    await page
      .getByRole("button", { name: /AI builders/ })
      .first()
      .click();
    const field = page.locator("#audience-builders .scene-field:visible");
    await expect(field.getByText("Workflow in use")).toBeVisible();
    const fit = await field.evaluate(readTextFit);
    expect(fit.map((label) => label.text)).toEqual(
      expect.arrayContaining([
        "Design",
        "Test",
        "Troubleshoot",
        "Anticipate failures",
        "Workflow in use",
      ]),
    );
    expect(wordProblems(fit)).toEqual([]);
    // Large enough to read on a narrow screen (docs/DESIGN.md: 13px).
    for (const label of fit)
      expect(label.fontSize, label.text).toBeGreaterThanOrEqual(13);
    const overlaps = await field.evaluate((element) => {
      const boxes = [...element.querySelectorAll(".system-label-text")].map(
        (label) => ({
          text: label.textContent,
          box: label.getBoundingClientRect(),
        }),
      );
      return boxes.flatMap((a, i) =>
        boxes
          .slice(i + 1)
          .filter(
            (b) =>
              a.box.left < b.box.right - 1 &&
              b.box.left < a.box.right - 1 &&
              a.box.top < b.box.bottom - 1 &&
              b.box.top < a.box.bottom - 1,
          )
          .map((b) => `${a.text} / ${b.text}`),
      );
    });
    expect(overlaps).toEqual([]);
  });
}

/**
 * What a person reads on the pinned builders stair at desktop widths: the
 * wide landscape composition a visitor with motion enabled actually sees.
 * Its step faces are narrow, so this is where "Troubleshoot" split midword.
 */
for (const [width, text] of [
  [1024, "100%"],
  [1024, "150%"],
  [1440, "100%"],
  [1440, "150%"],
  [1638, "100%"],
] as const) {
  test(`builder stair words stay whole on the pinned stair at ${width}px with ${text} text applied at load`, async ({
    page,
  }) => {
    // Full motion: the pinned landscape scene only shows with motion enabled.
    await page.addInitScript((size) => {
      const apply = () => {
        if (!document.documentElement) return false;
        document.documentElement.style.fontSize = size;
        return true;
      };
      if (!apply())
        new MutationObserver((_, watch) => {
          if (apply()) watch.disconnect();
        }).observe(document, { childList: true });
    }, text);
    await page.setViewportSize({ width, height: 900 });
    await page.goto("/");
    await page.evaluate(() => document.fonts.ready);
    await page.locator("#audiences").scrollIntoViewIfNeeded();
    await page
      .getByRole("button", { name: /AI builders/ })
      .first()
      .click();
    const field = page.locator(
      '.audience-art [data-audience-scene="2"] .scene-field',
    );
    await expect(field.getByText("Workflow in use")).toBeVisible();
    // Measure once the entrance has settled, not mid-animation.
    await expect
      .poll(
        async () =>
          field.evaluate((element) => {
            const words = [...element.querySelectorAll(".system-label")];
            const parts = [...element.querySelectorAll(".part")];
            const atRest = (el: Element) => {
              const style = getComputedStyle(el);
              return (
                style.opacity === "1" &&
                (style.transform === "none" ||
                  style.transform === "matrix(1, 0, 0, 1, 0, 0)")
              );
            };
            return {
              parts: parts.filter(
                (piece) => !atRest(piece.querySelector(".part-body") ?? piece),
              ).length,
              words: words.filter(
                (label) =>
                  !atRest(label.querySelector(".system-label-text") ?? label),
              ).length,
              animating: element.getAnimations({ subtree: true }).length,
            };
          }),
        { timeout: 20000 },
      )
      .toEqual({ parts: 0, words: 0, animating: 0 });
    const fit = await field.evaluate(readTextFit);
    expect(fit.map((label) => label.text)).toEqual(
      expect.arrayContaining([
        "Design",
        "Test",
        "Troubleshoot",
        "Anticipate failures",
        "Workflow in use",
      ]),
    );
    expect(wordProblems(fit)).toEqual([]);
    // Large enough to read (docs/DESIGN.md: 13px).
    for (const label of fit)
      expect(label.fontSize, label.text).toBeGreaterThanOrEqual(13);
    const layout = await field.evaluate((element) => {
      const box = element.getBoundingClientRect();
      const boxes = [...element.querySelectorAll(".system-label-text")].map(
        (label) => ({
          text: label.textContent,
          box: label.getBoundingClientRect(),
        }),
      );
      return { box, boxes };
    });
    const overlaps = layout.boxes.flatMap((a, i) =>
      layout.boxes
        .slice(i + 1)
        .filter(
          (b) =>
            a.box.left < b.box.right - 1 &&
            b.box.left < a.box.right - 1 &&
            a.box.top < b.box.bottom - 1 &&
            b.box.top < a.box.bottom - 1,
        )
        .map((b) => `${a.text} / ${b.text}`),
    );
    expect(overlaps).toEqual([]);
    // Nothing clips outside the drawing.
    for (const { text: labelText, box } of layout.boxes) {
      expect(box.left, labelText ?? "").toBeGreaterThanOrEqual(
        layout.box.left - 2,
      );
      expect(box.right, labelText ?? "").toBeLessThanOrEqual(
        layout.box.right + 2,
      );
      expect(box.top, labelText ?? "").toBeGreaterThanOrEqual(
        layout.box.top - 2,
      );
      expect(box.bottom, labelText ?? "").toBeLessThanOrEqual(
        layout.box.bottom + 2,
      );
    }
  });
}

for (const [width, height] of [
  [384, 686],
  [384, 742],
] as const) {
  test(`with scripting disabled the teams scene stays readable at ${width}×${height} [production]`, async ({
    browser,
  }) => {
    const context = await browser.newContext({
      javaScriptEnabled: false,
      viewport: { width, height },
    });
    const page = await context.newPage();
    // The production preview serves the prerendered pages as built.
    await page.goto("http://127.0.0.1:4179/website-redesign/");
    const panel = page.locator("#audience-contributors");
    const field = panel.locator(".scene-field:visible");
    await expect(field).toHaveCount(1);
    await expect(
      field.getByText("Reviewed work returns to each role."),
    ).toBeVisible();
    await expect(field.getByText("Human in the loop")).toBeVisible();
    // Measure in the webfont, not the fallback it shows while loading. Without
    // script the page cannot resolve `document.fonts.ready` (Firefox never
    // settles it), so poll the plain `status` from here instead.
    await expect
      .poll(() => page.evaluate(() => document.fonts.status))
      .toBe("loaded");
    const fit = await field.evaluate(readTextFit, [
      "skill1",
      "skill2",
      "skill3",
      "skill4",
    ]);
    expect(fit.length).toBeGreaterThan(0);
    expect(wordProblems(fit)).toEqual([]);
    // Large enough to read on a narrow screen (docs/DESIGN.md: 13px).
    for (const label of fit)
      expect(label.fontSize, label.text).toBeGreaterThanOrEqual(13);
    // The words are set on a drawing large enough to hold them.
    const size = await field.evaluate((el) => el.getBoundingClientRect().width);
    expect(size).toBeGreaterThan(300);
    expect(
      await page.evaluate(
        () => document.documentElement.scrollWidth <= innerWidth,
      ),
    ).toBe(true);
    await context.close();
  });
}
