import { readFileSync } from "node:fs";
import { test, expect, type Page } from "@playwright/test";
import { readField, type FieldState } from "./drawing";

/**
 * The redesigned drawings keep everything the deployed ones said.
 *
 * The fixture is an inventory of the drawings as deployed at the commit it
 * names, generated by `scripts/diagram-inventory.mjs` from that commit's own
 * modules: every word, its kind and its beat, every connection including the
 * feedback loops and the unlabelled branches, every mark on a person, a check
 * or a result, and each drawing's description and caption. The artwork was
 * redrawn from nothing; none of that was allowed to change.
 */

type Link = { from: string; to: string; weight: string };
type Inventory = {
  source: string;
  schematics: {
    id: string;
    description: string;
    nodes: { id: string; label: string; kind: string }[];
    flow: Record<"landscape" | "portrait", Link[]>;
  }[];
  scenes: {
    id: string;
    description: string;
    landscape: Scene;
    portrait: Scene;
  }[];
  captions: { id: string; caption: string }[];
};
type Scene = {
  labels: { text: string; kind: string; beat: number }[];
  marks: { kind: string; beat: number }[];
};

const inventory = JSON.parse(
  readFileSync(
    new URL("./fixtures/diagram-inventory.json", import.meta.url),
    "utf8",
  ),
) as Inventory;

/**
 * The scenes' connections, read from the deployed drawings' routes: which
 * piece each route ran from and to. The executive view feeds back to the
 * problem it answers; each role's skill answers to the human in the loop; the
 * builder's workflow is three linked parts; the review passes the three checks
 * in order before a person, then the business.
 */
const sceneLinks: Record<string, string[]> = {
  executives: [
    "problem>skill",
    "skill>brief",
    "brief>view",
    "direction>view",
    "view>problem",
  ],
  contributors: [1, 2, 3, 4].flatMap((n) => [
    `role${n}>skill${n}`,
    `skill${n}>human`,
  ]),
  builders: [
    "learner>test",
    "test>troubleshoot",
    "troubleshoot>anticipate",
    "anticipate>workflow",
    "workflow>blocks",
  ],
  review: [
    "draft>weak",
    "weak>missing",
    "missing>false",
    "false>review",
    "review>business",
  ],
};

const drawnLinks = (state: FieldState) =>
  [...new Set(state.parts.flatMap((piece) => piece.links))].sort();
const drawnNodes = (state: FieldState) =>
  new Set(state.parts.flatMap((piece) => piece.nodes));
const drawnMarks = (state: FieldState) =>
  state.parts
    .flatMap((piece) =>
      piece.marks.map((mark) => `${mark.split(":")[0]}@${piece.beat}`),
    )
    .sort();

async function open(page: Page, path: string, width: number) {
  await page.setViewportSize({ width, height: width < 700 ? 844 : 900 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto(path);
  await page.evaluate(() => document.fonts.ready);
}

function expectSchematic(
  state: FieldState,
  id: string,
  orientation: "landscape" | "portrait",
) {
  const expected = inventory.schematics.find((s) => s.id === id)!;
  const where = `${id} ${orientation}`;
  expect(state.describedBy, where).toBe(expected.description);
  expect(
    state.labels.map(({ node, text, kind }) => ({ node, text, kind })),
    where,
  ).toEqual(
    expected.nodes.map(({ id: node, label, kind }) => ({
      node,
      text: label,
      kind,
    })),
  );
  // Exactly the connections the deployed drawing made — no fewer, and none
  // invented — including its return loop and its unnamed outputs.
  expect(drawnLinks(state), where).toEqual(
    [
      ...new Set(
        expected.flow[orientation].map((link) => `${link.from}>${link.to}`),
      ),
    ].sort(),
  );
  const nodes = drawnNodes(state);
  for (const node of expected.nodes)
    expect(nodes.has(node.id), `${where}: a piece stands for ${node.id}`).toBe(
      true,
    );
}

function expectScene(
  state: FieldState,
  id: string,
  orientation: "landscape" | "portrait",
) {
  const expected = inventory.scenes.find((s) => s.id === id)!;
  const where = `${id} ${orientation}`;
  expect(state.describedBy, where).toBe(expected.description);
  expect(
    state.labels.map(({ text, kind, beat }) => ({ text, kind, beat })),
    where,
  ).toEqual(expected[orientation].labels);
  expect(drawnMarks(state), where).toEqual(
    expected[orientation].marks
      .map((mark) => `${mark.kind}@${mark.beat}`)
      .sort(),
  );
  expect(drawnLinks(state), where).toEqual([...sceneLinks[id]].sort());
}

test("the fixture is the deployed drawings' inventory", () => {
  expect(inventory.source).toBe("40e42eb");
  expect(inventory.schematics.map((s) => s.id)).toEqual([
    "master",
    "training",
    "automation",
    "product",
  ]);
  expect(inventory.scenes.map((s) => s.id)).toEqual([
    "executives",
    "contributors",
    "builders",
    "review",
  ]);
});

test("the opening drawing keeps its words and connections in both shapes", async ({
  page,
}) => {
  await open(page, "/", 1440);
  expectSchematic(
    await page.locator(".hero-art .system-field").evaluate(readField),
    "master",
    "landscape",
  );
  await open(page, "/", 1024);
  expectSchematic(
    await page.locator(".hero-art .system-field").evaluate(readField),
    "master",
    "portrait",
  );
  await open(page, "/industries/private-equity/", 1440);
  expectSchematic(
    await page.locator(".page-drawing .system-field").evaluate(readField),
    "master",
    "portrait",
  );
});

test("each service drawing keeps its words and connections in both shapes", async ({
  page,
}) => {
  await open(page, "/", 1440);
  const services = [
    ["training", "Workshops"],
    ["automation", "Workflows"],
    ["product", "Automations"],
  ] as const;
  for (const [id, choice] of services) {
    const button = page.getByRole("button", { name: choice, exact: true });
    await button.click();
    await expect(button).toHaveAttribute("aria-pressed", "true");
    await expect
      .poll(() =>
        page
          .locator(".services-art .system-field")
          .evaluate((field) => field.getAttribute("aria-label")),
      )
      .toBe(inventory.schematics.find((s) => s.id === id)!.description);
    expectSchematic(
      await page.locator(".services-art .system-field").evaluate(readField),
      id,
      "landscape",
    );
    // Each article's own drawing is its portrait composition.
    expectSchematic(
      await page
        .locator(`#service-${id} .service-figure .system-field`)
        .evaluate(readField),
      id,
      "portrait",
    );
  }
  // And the same once a narrow layout has mounted them live.
  await open(page, "/", 390);
  for (const [id] of services)
    expectSchematic(
      await page
        .locator(`#service-${id} .service-figure .system-field`)
        .evaluate(readField),
      id,
      "portrait",
    );
});

test("each audience scene keeps its words, marks, beats and connections", async ({
  page,
}) => {
  for (const [width, orientation] of [
    [1440, "landscape"],
    [390, "portrait"],
  ] as const) {
    await open(page, "/", width);
    for (const id of ["executives", "contributors", "builders"]) {
      const panel = page.locator(`#audience-${id}`);
      expectScene(
        await panel.locator(".scene-field").evaluate(readField),
        id,
        orientation,
      );
      await expect(panel.locator(".audience-caption")).toHaveText(
        inventory.captions.find((c) => c.id === id)!.caption,
      );
    }
    await open(page, "/resources/", width);
    expectScene(
      await page.locator(".review-figure .scene-field").evaluate(readField),
      "review",
      orientation,
    );
  }
});

test("nothing draws itself, runs along a line, or loops", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);

  /**
   * Every animation a drawing starts, sampled while the opening drawing is
   * assembled, while a service drawing changes and while a scene is told. A
   * piece is placed — it may fade, move, turn or scale into its place — and
   * then it is still: no stroke is drawn on, nothing travels along a path,
   * nothing repeats.
   */
  const sample = () =>
    page.evaluate(() =>
      document
        .getAnimations()
        .filter((animation) => {
          const target = (animation.effect as KeyframeEffect | null)?.target;
          return !!target?.closest(".system-field");
        })
        .map((animation) => {
          const effect = animation.effect as KeyframeEffect;
          return {
            properties: [
              ...new Set(
                effect
                  .getKeyframes()
                  .flatMap((frame) => Object.keys(frame))
                  .filter(
                    (key) =>
                      ![
                        "offset",
                        "computedOffset",
                        "easing",
                        "composite",
                      ].includes(key),
                  ),
              ),
            ].sort(),
            iterations: effect.getTiming().iterations,
          };
        }),
    );

  const seen: Awaited<ReturnType<typeof sample>> = [];
  seen.push(...(await sample()));
  await page.waitForTimeout(300);
  seen.push(...(await sample()));

  await page.locator("#services").scrollIntoViewIfNeeded();
  await page.getByRole("button", { name: "Automations", exact: true }).click();
  await page.waitForTimeout(150);
  seen.push(...(await sample()));
  await page.waitForTimeout(350);
  seen.push(...(await sample()));

  await page.locator("#audiences").scrollIntoViewIfNeeded();
  await page.getByRole("button", { name: /AI builders/ }).click();
  await page.waitForTimeout(200);
  seen.push(...(await sample()));

  expect(seen.length, "the drawings were sampled mid-entrance").toBeGreaterThan(
    0,
  );
  for (const animation of seen) {
    expect(
      animation.properties.every((key) =>
        ["opacity", "transform"].includes(key),
      ),
      JSON.stringify(animation),
    ).toBe(true);
    expect(animation.iterations).toBe(1);
  }
  // Nor is anything built to travel: no moving signal, no SMIL.
  await expect(
    page.locator(
      ".system-field :is(.signal, .route, animate, animateMotion, animateTransform)",
    ),
  ).toHaveCount(0);
});

test("an assembled drawing rests exactly where a still one does", async ({
  page,
  context,
}) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);
  const still = await context.newPage();
  await still.setViewportSize({ width: 1440, height: 900 });
  await still.emulateMedia({ reducedMotion: "reduce" });
  await still.goto("/");
  await still.evaluate(() => document.fonts.ready);

  const read = (target: Page) =>
    target.locator(".hero-art .system-field").evaluate(readField);
  await expect
    .poll(async () => {
      const state = await read(page);
      return { ...state.unsettled, animating: state.animating };
    })
    .toEqual({ parts: 0, words: 0, animating: 0 });
  expect(await read(page)).toEqual(await read(still));
  await still.close();
});

test("the opening words never cover the drawing, at any width", async ({
  page,
}) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  for (const width of [
    1920, 1440, 1280, 1180, 1179, 1100, 1024, 961, 900, 861, 860, 768, 430, 390,
    320,
  ]) {
    await page.setViewportSize({ width, height: 900 });
    await page.goto("/");
    await page.evaluate(() => document.fonts.ready);
    const overlaps = await page.evaluate(() => {
      const art = document
        .querySelector(".hero-art .system-field")!
        .getBoundingClientRect();
      const meet = (a: DOMRect, b: DOMRect) =>
        a.left < b.right - 0.5 &&
        b.left < a.right - 0.5 &&
        a.top < b.bottom - 0.5 &&
        b.top < a.bottom - 0.5;
      const words = [
        ...document.querySelectorAll(
          ".hero-copy h1, .hero-copy p, .hero-actions .action, .hero-proof p, .hero-proof blockquote, .hero-proof figcaption",
        ),
      ];
      return {
        covered: words
          .filter((word) => meet(word.getBoundingClientRect(), art))
          .map((word) => word.textContent?.trim().slice(0, 40)),
        art: { width: art.width, height: art.height },
        // The drawing's own words stay inside the page.
        outside: [
          ...document.querySelectorAll(".hero-art .system-label-text"),
        ].filter((label) => {
          const box = label.getBoundingClientRect();
          return box.left < 0 || box.right > innerWidth;
        }).length,
      };
    });
    expect(overlaps.covered, `${width}px`).toEqual([]);
    expect(overlaps.outside, `${width}px`).toBe(0);
    expect(overlaps.art.width, `${width}px`).toBeGreaterThan(200);
  }
});
